[plugin]  
prepend_previewers = [  
  # Rich Previewer config
  { url = "*.csv", run = "rich-preview"}, # for csv files
  { url = "*.tsv", run = "rich-preview"}, # for csv files
  { url = "*.md", run = "rich-preview" }, # for markdown (.md) files
  { url = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
  { url = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
  { url = "*.json", run = "rich-preview"}, # for json (.json) files
  { url = "*.toml", run = "rich-preview"}, # for toml (.toml) files
  { url = "*.yaml", run = "rich-preview"}, # for yaml (.yaml) files
  { url = "*.py", run = "rich-preview"}, # for python (.py) files
  { url = "*.nix", run = "rich-preview"}, # for nix (.nix) files
  { url = "*.json", run = "rich-preview"}, # for json (.json) files
  # { url = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.

  # DuckDB Previewer config
  # { url = "*.csv", run = "duckdb" },  
  # { url = "*.tsv", run = "duckdb" },  
  # { url = "*.json", run = "duckdb" },  
  { url = "*.parquet", run = "duckdb" },  
  { url = "*.prq", run = "duckdb" },  
  { url = "*.xlsx", run = "duckdb" },  
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" }
]

prepend_preloaders = [
  # { url = "*.csv", run = "duckdb", multi = false },
  # { url = "*.tsv", run = "duckdb", multi = false },
  # { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.prq", run = "duckdb", multi = false },  
  { url = "*.xlsx", run = "duckdb", multi = false }
]

# Git Previewer Plugin
[[plugin.prepend_fetchers]]
group = "git"
url  = "*"
run  = "git"

[[plugin.prepend_fetchers]]
group = "git"
url  = "*/"
run  = "git"