# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/431623d5-bd12-4a53-a051-c7e6789d3725";
    fsType = "ext4";
  };

  fileSystems."/mnt/depo_1" = {
    device = "/dev/disk/by-uuid/3531f8b1-e82e-401b-b897-7e3325e08ccf";
    fsType = "ext4";
  };

  fileSystems."/mnt/nvme" = {
    device = "/dev/disk/by-uuid/ce2c5440-f2df-44ad-b9c1-e27255982a33";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/f950f24e-4c37-47ae-ab5f-7e96f1ef1f5f"; }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
